#!/usr/bin/perl

use 5.16.0;
use strict;
use warnings;

use lib "./src";
use RiveScript;
use RiveScript::HTTPd;

# Create the HTTP daemon.
my $daemon = RiveScript::HTTPd->new(
	address => '127.0.0.1',
	port    => 2006,
	debug   => 0,

	document_root => './public_html',
	cgi_scripts   => [ '.cgi', '.pl', '.py' ],
);

say "Just a moment while I check whether you have Perl and Python installed...\n";

# Help it find Perl and Python.
my $perl   = $daemon->find_interpreter("perl", "/usr/bin/perl", [
	'C:/Perl/bin/perl.exe',
]);
my $python = $daemon->find_interpreter("python", "/usr/bin/python", [
	'C:/Python25/python.exe',
	'C:/Python27/python.exe',
]);

# Results?
perl() unless $perl;
python() unless $python;

my $url = $daemon->url();
say "All set! The server is listening on $url";
say "Visit that URL in your browser now.";
$daemon->start();

sub perl {
	say qq{I didn't find a Perl interpreter installed on your system.
This is okay as long as you only use the Perl CGI scripts that come with
RiveScript-HTTPd, as this server should be able to execute them by itself.
However, you may get better performance out of it by installing a Perl
interpreter. You can get one from www.activeperl.com
};
}

sub python {
	say qq{I didn't find a Python interpreter installed on your system.
This means that you won't be able to test and work with the Python CGI scripts
for RiveScript. The Perl CGI and JavaScript interfaces to RiveScript should
still work just fine, though. You can get a Python interpreter from
www.python.org
};
}
